#!/usr/bin/env ruby

# hex2cine -- script for converting a hex-dump file to a CINE file
#     (for use with the appendix data in the documentation.)
#
# part of vrptools -- https://github.com/lindes/vrptools
#
# Copyright 2011 by David Lindes.  All rights reserved.
#
# Available under terms in the LICENSE file that should accompany
# this file.  Please consider that file to be included herein by
# reference.

ARGV.each do |filename|
  outname = filename.sub(/.txt$/, '.cine')
  if(File.exists?(outname))
    warn "Sorry, #{outname} exists; won't convert #{filename}"
    next
  end

  infile = File.open(filename)
  outfile = File.open(outname, 'wb')
  warn "Converting #{filename} from hex to binary, into #{outname}"
  infile.each_line do |line|
    line.sub!(/#.*/, '')
    next if line =~ /^\s*$/
    (addr, data) = line.split(/\s+/, 2)
    if(addr !~ /^[\dA-F]{8}$/)
      warn "Warning: unruly line: #{line}"
      next
    end
    outfile.seek(addr.hex.to_i) # in case of gaps, which there are a couple of.
    data = data.split(/\s+/)
    if(data.size != 16 and !infile.eof?)
      warn "Warning: line has bad data size #{data.size}, should be 16:\n\t#{line}"
    end
    outfile.syswrite(data.pack('H2' * data.size))
  end
end
